// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: transport/internet/qstunnel/config.proto

package qstunnel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client-side
	Domain        string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`                                       // DNS domain suffix for encoding data
	FakeSendIp    string `protobuf:"bytes,2,opt,name=fake_send_ip,json=fakeSendIp,proto3" json:"fake_send_ip,omitempty"`           // Spoofed source IP for download responses
	FakeSendPort  uint32 `protobuf:"varint,3,opt,name=fake_send_port,json=fakeSendPort,proto3" json:"fake_send_port,omitempty"`    // Spoofed source port (default 443)
	MaxDomainLen  uint32 `protobuf:"varint,4,opt,name=max_domain_len,json=maxDomainLen,proto3" json:"max_domain_len,omitempty"`    // Max encoded domain length (default 253)
	MaxSubLen     uint32 `protobuf:"varint,5,opt,name=max_sub_len,json=maxSubLen,proto3" json:"max_sub_len,omitempty"`             // Max DNS label length (default 63)
	MyPublicIp    string `protobuf:"bytes,6,opt,name=my_public_ip,json=myPublicIp,proto3" json:"my_public_ip,omitempty"`           // Client's public IP
	Retries       uint32 `protobuf:"varint,7,opt,name=retries,proto3" json:"retries,omitempty"`                                    // Retry count per send
	SendSockCount uint32 `protobuf:"varint,9,opt,name=send_sock_count,json=sendSockCount,proto3" json:"send_sock_count,omitempty"` // Number of UDP send sockets (default 512)
	// Server-side
	RecvDomains   []string `protobuf:"bytes,8,rep,name=recv_domains,json=recvDomains,proto3" json:"recv_domains,omitempty"` // Accepted domain suffixes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_transport_internet_qstunnel_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_transport_internet_qstunnel_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_transport_internet_qstunnel_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Config) GetFakeSendIp() string {
	if x != nil {
		return x.FakeSendIp
	}
	return ""
}

func (x *Config) GetFakeSendPort() uint32 {
	if x != nil {
		return x.FakeSendPort
	}
	return 0
}

func (x *Config) GetMaxDomainLen() uint32 {
	if x != nil {
		return x.MaxDomainLen
	}
	return 0
}

func (x *Config) GetMaxSubLen() uint32 {
	if x != nil {
		return x.MaxSubLen
	}
	return 0
}

func (x *Config) GetMyPublicIp() string {
	if x != nil {
		return x.MyPublicIp
	}
	return ""
}

func (x *Config) GetRetries() uint32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *Config) GetSendSockCount() uint32 {
	if x != nil {
		return x.SendSockCount
	}
	return 0
}

func (x *Config) GetRecvDomains() []string {
	if x != nil {
		return x.RecvDomains
	}
	return nil
}

var File_transport_internet_qstunnel_config_proto protoreflect.FileDescriptor

const file_transport_internet_qstunnel_config_proto_rawDesc = "" +
	"\n" +
	"(transport/internet/qstunnel/config.proto\x12 xray.transport.internet.qstunnel\"\xb5\x02\n" +
	"\x06Config\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12 \n" +
	"\ffake_send_ip\x18\x02 \x01(\tR\n" +
	"fakeSendIp\x12$\n" +
	"\x0efake_send_port\x18\x03 \x01(\rR\ffakeSendPort\x12$\n" +
	"\x0emax_domain_len\x18\x04 \x01(\rR\fmaxDomainLen\x12\x1e\n" +
	"\vmax_sub_len\x18\x05 \x01(\rR\tmaxSubLen\x12 \n" +
	"\fmy_public_ip\x18\x06 \x01(\tR\n" +
	"myPublicIp\x12\x18\n" +
	"\aretries\x18\a \x01(\rR\aretries\x12&\n" +
	"\x0fsend_sock_count\x18\t \x01(\rR\rsendSockCount\x12!\n" +
	"\frecv_domains\x18\b \x03(\tR\vrecvDomainsB\x82\x01\n" +
	"$com.xray.transport.internet.qstunnelP\x01Z5github.com/xtls/xray-core/transport/internet/qstunnel\xaa\x02 Xray.Transport.Internet.Qstunnelb\x06proto3"

var (
	file_transport_internet_qstunnel_config_proto_rawDescOnce sync.Once
	file_transport_internet_qstunnel_config_proto_rawDescData []byte
)

func file_transport_internet_qstunnel_config_proto_rawDescGZIP() []byte {
	file_transport_internet_qstunnel_config_proto_rawDescOnce.Do(func() {
		file_transport_internet_qstunnel_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_internet_qstunnel_config_proto_rawDesc), len(file_transport_internet_qstunnel_config_proto_rawDesc)))
	})
	return file_transport_internet_qstunnel_config_proto_rawDescData
}

var file_transport_internet_qstunnel_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transport_internet_qstunnel_config_proto_goTypes = []any{
	(*Config)(nil), // 0: xray.transport.internet.qstunnel.Config
}
var file_transport_internet_qstunnel_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transport_internet_qstunnel_config_proto_init() }
func file_transport_internet_qstunnel_config_proto_init() {
	if File_transport_internet_qstunnel_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_internet_qstunnel_config_proto_rawDesc), len(file_transport_internet_qstunnel_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_internet_qstunnel_config_proto_goTypes,
		DependencyIndexes: file_transport_internet_qstunnel_config_proto_depIdxs,
		MessageInfos:      file_transport_internet_qstunnel_config_proto_msgTypes,
	}.Build()
	File_transport_internet_qstunnel_config_proto = out.File
	file_transport_internet_qstunnel_config_proto_goTypes = nil
	file_transport_internet_qstunnel_config_proto_depIdxs = nil
}
